### ISSUE TITLE
5-fold cross-validation results

### ISSUE THREAD

**Issue by FabianIsensee** [xmed-lab/TriALS#1]
Hey there,

thanks a lot for the repo! It's really useful to have all these methods in one place.
When looking through the results I was a bit confused though: The lesion scores are way higher and the Liver scores are way lower than what we have in our internal validation of most of these models. Also the 2D model is usually a lot worse than the 3D nnU-Net. Can you be more specific how these scores were computed? Are you using the same folds as nnU-Net and averaging over all five folds? How are the metrics computed?

This is what we are getting with the current nnU-Net 3d_fullres for Liver and Lesion. Dice computed on each image separately and then averaged over images:
fold0: 0.9651	0.6547
fold1: 0.9613	0.5669
fold2: 0.9509	0.6783
fold3: 0.9574	0.7061
fold4: 0.9515	0.5955
Average: 0.9572	0.6403

These numbers are consistent with the results reported in our [supplement](https://static-content.springer.com/esm/art%3A10.1038%2Fs41592-020-01008-z/MediaObjects/41592_2020_1008_MOESM1_ESM.pdf):  0.9576 0.6253

Just an idea: It would be really useful to extend the table with computational requirements to that users know what they are getting into. GPU hours required for training and VRAM requirements can help a lot to put results into perspective

Best,
Fabian

**Comment by marwankefah** [comment]
Hi Fabian,

First off, I would like to thank you for the invaluable contributions of nnU-Net and its flexibility, which have greatly benefited our hybrid human-AI annotation process within our dataset.

Currently, I'm working with the [LiTs evaluation code](https://github.com/xmed-lab/TriALS/tree/main/evaluation), and I've observed that it reports the ``lesion dice`` as an average across all lesions. To avoid confusion, we've made this note in our ReadMe, along with a reference link to the full [model_summary_metrics.csv](https://github.com/xmed-lab/TriALS/blob/main/evaluation/LiTS_metrics_summary.csv).

In our analysis, the standout model based on ``lesion dice per case`` is ``MedNext-L-5``, with a score of ``0.5780 (±0.0635)``. The 2D nnU-Net model has more competitive results than its 3D counterparts, with the latter scoring ``0.5117 (±0.0405)``, which is beneath the benchmark of 0.6403.

I speculate that the discrepancy might stem from **the split** as well as the different training durations, specifically, running the benchmark for **100 epochs rather than 1000**, possibly leading to under-convergence in the 3D nnU-Net. I have also highlighted this in the ReadMe model training.

I've uploaded the output of running ``nnUNetv2_plan_and_preprocess`` for your reference [here](https://github.com/xmed-lab/TriALS/tree/main/data/nnUNet_preprocessed/Dataset003_Liver). 

Would you be able to confirm the plan generated and the specific data splits follow your internal validation?

I should extend the table with the computational requirements. 

Thank you for your time and support.

Warm regards,

Marawan

**Comment by FabianIsensee** [comment]
Hey Marawan,
thanks a lot for the clarifications, also in the readme. Since the repository is advertised as a starting point for participating in challenges the provided benchmarks will help users a lot in putting their results into perspective. In that context it might be sub-optimal though to make model recommendations based on very short runs, without clearly outlining that immediately next to the table. You probably don't want to point your participants in a wrong direction by suggesting that a 2D model can be competitive on your data. It could also be useful to directly link the evaluation code next to the csv so that one can immediately see what was being done.
One thing I am not happy with is the fact that the standard nnUNetTrainer was modified in this repository to only run for 100 epochs. This is no longer the nnU-Net and should not be listed in a way that would suggest it is. Users will use this repository thinking it is the nnU-Net and then be dissatisfied with the performance. It would have been more transparent to leave all the nnU-Net trainers untouched and to create new ones for each specific purpose: nnUNetTrainer_100epochs, nnUNetTrainerSAMed, nnUNetTrainerSAMed_100epochs, .... These could then also be listed in the benchmarking table to make it perfectly transparent what is being measured.
Thanks a lot for putting all of this together! The challenge looks super interesting and you might see a submission from our side as well ;-)
Best,
Fabian

**Comment by marwankefah** [comment]
Aloha Fabian,

To eliminate any confusion among users, I've made necessary adjustments to the trainers and added the epoch count next to the relevant table. Given the request for a benchmark set at 1000 epochs, it's clear that this process is both time and compute-intensive (the purpose of this repo is to assist users, not to promote a competitive environment with an optimal performance). Currently, I'm allocating time to run all models at 1000 epochs.

Notably, after completing the 5-fold for 3D nnU-Net in about 60 hours, roughly equating to 2.5 days, we observed higher KPIs on our [data split](https://github.com/xmed-lab/TriALS/blob/main/data/nnUNet_preprocessed/Dataset003_Liver/splits_final.json) compared to the results you've reported.

 [metrics_summary](https://github.com/xmed-lab/TriALS/blob/main/evaluation/LiTS_metrics_summary_1000epochs.csv): ``liver dice per case: 0.9628 (±0.0062)`` and ``lesion dice per case: 0.6698 (±0.0560)`` 

This outcome prompted another table in the [ReadMe](https://github.com/xmed-lab/TriALS/blob/main/README.md), reflecting these findings. We plan to update this table further with the results, model weights, VRAM for the all baselines once those are finalized.

Thank you for your suggestions and interest, and I look forward to your participation in the challenge.

Warm regards,
Marawan
